services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/chatdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass

  postgresdb:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-testdb:
    image: postgres:17-alpine
    container_name: postgres-test-db
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    profiles: ["test"]

  tester:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: build
    container_name: spring-boot-tests
    ports:
      - "7070:7070"
    depends_on:
      - postgres-testdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-testdb:5432/testdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    entrypoint: ["mvn", "clean","test"]
    profiles: ["test"]

volumes:
  postgres_data:
  postgres_test_data: